### ISSUE TITLE
Test file raises NameError: uninitialized constant GildedRoseTest::Item 

### ISSUE THREAD

**Issue by Rohianon** [simonneutert/gilded_rose_kata#1]
I am trying to use the command mentioned to run the test file like this 
`ruby -Itest gilded_rose_test.rb`. 
However I end up with the following error.
![image](https://github.com/simonneutert/gilded_rose_kata/assets/41194018/456d427b-8858-49fc-8974-ce07a75bafa5)

How could this be resolved?

**Comment by simonneutert** [comment]
Hi @Rohianon thank you for reaching out.

Some subdirectories may or may not throw errors. 

I added a sentence in the Readme.md mentioning that `07_extending` will work for sure :v:

So, I see you are doing it in a rails project. So, in this case you need to make sure your class is loaded. 

Let me guide you into what you may need to make rails7 load your custom code.

https://guides.rubyonrails.org/autoloading_and_reloading_constants.html

Btw naming of the files is crucial in rails, so please make sure you didn't make a mistake there 🤓 

Good luck 🤞

**Comment by Rohianon** [comment]
Thanks a lot Simon fo the deep insights here.
I am actually trying to do ruby this second half of the year after learning
React for the first half.
Thanks for the link as well.
Will let you know how it goes.

Warm Regards,
Rohi Anon Ogula

*Phone: +254795632662*
*Email: ***@***.*** ***@***.***>*

*Linked-in <https://www.linkedin.com/in/rohi-anon-38a026167/>.*
*Git-Hub Portfolio.* <https://github.com/Rohianon>
*Medium ***@***.***>.*

**Comment by simonneutert** [comment]
I highly recommend Ruby if you plan to develop web software. Feel free to browse through my GitHub profile for Ruby projects for some inspiration. 

Stick with it. Learning to program can be very frustrating at times. Even being familiar with programming won’t help. 

But the reward is you will be able to express yourself with code and make the life of you and others better. 

Please reach out if you need help. If I find the time I will try and give you a helping hand.
